### ISSUE TITLE
n06_equations_of_motion // cannot unpack non-iterable RigidBody object

### ISSUE THREAD

**Issue by miercat0424** [pydy/pydy-tutorial-human-standing#119]
Hi, I'm following the 2016 "Simulating Robot ~~" tutorial video 
and i stuck on

https://www.youtube.com/watch?v=r4piIKV4sDw&t=6375s
1:51:28
here 

fr , frstar = kane.kanes_equations(loads,bodies) 
>>>  TypeError : cannot unpack non-iterable RigidBody object 

it shows different result from the video

can you help me ?

**Comment by moorepants** [comment]
If you are using a newer version of SymPy the API has changed:

`kanes_equations(bodies, loads)`

See: https://docs.sympy.org/latest/modules/physics/mechanics/api/kane_lagrange.html#sympy.physics.mechanics.kane.KanesMethod.kanes_equations

**Comment by miercat0424** [comment]
Thanks! 
I changed 
>> fr, frstar = kane.kanes_equations(**loads , bodies**) 
to 
>> fr, frstar = kane.kanes_equations(bodies , loads)
it works ! 
I love that tutorial thanks a lot ! have a nice day
