### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-tutorial-human-standing#58]
@pydy/pydy-developers I'd like to rename this repo to something like `pydy-standing-tutorial` and then continue to use branches and tags for the various versions that we give at different places with the HEAD of master being the most generic version.

Any suggestions on names for the repo? Is this fine?

Github will redirect (maybe indefinitely) so it shouldn't break links.

**Comment by chrisdembia** [comment]
`pydy-tutorial-human-standing` `pydy-standing-tutorial` made me think of the "in continual use" meaning of "standing".

**Comment by moorepants** [comment]
Good point, thanks.
