### ISSUE TITLE
Update the control notebook to use KanesMethod.linearize()

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-tutorial-human-standing#77]
We should get rid of all the details about manually linearizing and just use the method.

**Comment by moorepants** [comment]
@jcrist Would you want to do this? Or shall we leave it as is?

**Comment by jcrist** [comment]
I can take care of this.

**Comment by moorepants** [comment]
@jcrist The milestone due dates for the release of 0.3.0 and this updated tutorial are today. What's the status on your contributions?

**Comment by jcrist** [comment]
Woops, forgot about this. I'll make sure to do it tonight, shouldn't take too long.

**Comment by moorepants** [comment]
Ok, I'm hoping to send SciPy the updated materials by tomorrow. We'll see what I can get done.

Also we should touch base this week to discuss the tutorial and how we are going to present it (who does what, etc.).

**Comment by oliverlee** [comment]
Will this be livestreamed/recorded?

**Comment by moorepants** [comment]
Yes, it will be available on Youtube soon after the conference.

**Comment by moorepants** [comment]
You should see if Arend will fund you to come over!

**Comment by oliverlee** [comment]
Maybe next year

**Comment by jcrist** [comment]
Many of the exercises in this notebook have them doing the linearization manually. I kindof think those are good exercises, and am not sure what to do instead. What are your thoughts on this?

**Comment by moorepants** [comment]
We can leave it as is if you want. Maybe just show at the end that you can also do it automatically?

**Comment by jcrist** [comment]
See how I did it in #81 - this may be good enough, idk.
