### ISSUE TITLE
Make sure the exploratory exercise works in the controls notebook

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-tutorial-human-standing#84]
The default weights do not work now that the linearizer is used.

**Comment by jcrist** [comment]
Blarg. I can't seem to figure out the failure in this, and it's getting late here. Will work on it again tomorrow.

Possible bugs:
1. Linearizer gives wrong result (shudder :frowning:)
2. I goofed up something else in the n09 notebook fix, and it's percolated down.
3. Original code performed the linearization incorrectly, and with a correct linearization the controller fails

Either way, the A and B matrices don't line up with the values from before

**Comment by moorepants** [comment]
Hmm, I'll have a look too. This sounds similar to how things changed in the npendulum example when I updated it for the new linearizer.

**Comment by moorepants** [comment]
Can this be fixed by passing in SymPy objects in as the equilibrium dict instead of Python floats?

**Comment by moorepants** [comment]
I didn't get to this tonight. Will check it out in the morning.

**Comment by moorepants** [comment]
Let's just remove the non-working exercise and close this.
