### ISSUE TITLE
n05_kinetics misses the import

### ISSUE THREAD

**Issue by soupault** [pydy/pydy-tutorial-human-standing#99]
`from sympy import symbols` should be casted in the `Setup` section.

**Comment by soupault** [comment]
Also, `from solution.inertia import *` is missing.

**Comment by oliverlee** [comment]
The first code box has the ```solution.inertia``` import:

```python
from __future__ import print_function, division
from solution.inertia import *
```

The import of ```solution.inertia``` imports ```solution.kinematics``` which then import ```symbols```.

Can you give steps to reproduce your problem?

**Comment by soupault** [comment]
Yes, sorry, you are right. Probably, I've went throught the cells too fast. Anyways, direct import of `symbols` could be good for the transparency.
